### ISSUE TITLE
How can I capture a crash in dynamic library?

### ISSUE THREAD

**Issue by lunexnocty** [google/fuzzing#24]
I tried the example fuzz_me.c and run it as tutorial like, it crashed soon.

I created a header file `fuzz_me.h` and compile `fuzz_me.cc` to `libfuzz_me.so` with compile-flag `-fsanitize=address`. Then I called `FuzzMe()` by dynamic library. However it couldn't trigger the crash.

But when I changed the Actual parameter `Size` to 3 in file `myfuzzer.cc` at line 5, it crashed again.
 
Codes:
```cc
/****************************************************
* fuzz_me.cc
****************************************************/
#include <stdint.h>
#include <stddef.h>
bool FuzzMe(const uint8_t *Data, size_t DataSize) {
  return DataSize >= 3 &&
      Data[0] == 'F' &&
      Data[1] == 'U' &&
      Data[2] == 'Z' &&
      Data[3] == 'Z';  // :‑<
}
/****************************************************
* fuzz_me.h
****************************************************/
#include <stdint.h>
#include <stddef.h>
bool FuzzMe(const uint8_t *Data, size_t DataSize);
/****************************************************
* myfuzzer.h
****************************************************/
#include <stdint.h>
#include <stddef.h>
#include "fuzzme.h"
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  FuzzMe(Data, Size);
  return 0;
}
```
```sh
clang -shared -o libfuzzme.so fuze_me.cc -fsanitize=address
clang -fsanitize=address,fuzzer -o myfuzzer ./myfuzzer.cc -L. -llibfuzzme
```

**Comment by Dor1s** [comment]
In you first compilation command use `-fsanitize=address,fuzzer-no-link`.

`-fsanitize=fuzzer-no-link` part enables important coverage instrumentation, which is crucial for fuzzer to make progress.

`-fsanitize=fuzzer` argument enables that instrumentation too, but it also links whatever you compiling with libFuzzer itself and therefore produces an executable fuzz target binary. That's why `-fsanitize=fuzzer` should still be used in the second command, where you actually produce a binary.

**Comment by lunexnocty** [comment]
I'd tried and it worked! Thank you very much.
