### ISSUE TITLE
Libfuzzer Time complexity 

### ISSUE THREAD

**Issue by fatimahkj** [google/fuzzing#67]
Hi, 

Is there any paper which explains time complexity (using big o) for libfuzzer? 
If not, how can I get the libfuzzer complexity?

**Comment by kcc** [comment]
No such paper.
In most cases, libFuzzer's own overhead is negligible compared to the time spent executing the target code. 
If the binary is huge, you may start noticing libFuzzer's own functions in the profile, 
because libFuzzer has some O(SizeOfTheBinary) operations.  

hope this help (feel free to reopen with more questions)
